Repository xsf/xeps, pull requests merged in 2018-05, with the labels that each got.

#626 XEP-0393: clarify language around strong emphasis
  xep-0393.xml
Labels: Editorial Change, Ready To Merge

#630 XEP-0369: fix examples and some styles
  xep-0369.xml
Labels: Editorial Change, Needs Version Block, Ready To Merge

#631 xep-0384: fix attribute names in schema
  xep-0384.xml
Labels: Editorial Change, Needs Version Block, Ready To Merge

#634 XEP-0373: Fix link to RFC-4880 §11.2. Transferable Secret Keys
  xep-0373.xml
Labels: Editorial Change, Needs Version Block, Ready To Merge

#642 Editorial - XEP-0369
  xep-0369.xml
Labels: Editorial Change, Ready To Merge

#645 XEP-0401: Typo in example 5 title
  xep-0401.xml
Labels: Editorial Change, Ready To Merge

#646 XREP-0369 Mandatory/Optional table
  xep-0369.xml
Labels: Editorial Change, Ready To Merge

#647 Fix example - XEP-0369
  xep-0369.xml
Labels: Editorial Change, Ready To Merge

#648 Fix a typo in XEP-0334
  xep-0334.xml
Labels: Editorial Change, Ready To Merge

#649 Fix a typo in XEP-0313
  xep-0313.xml
Labels: Editorial Change, Ready To Merge

#651 xep-0363: refine error conditions
  xep-0363.xml
Labels: Ready To Merge
