Repository xsf/xeps, pull requests merged in 2018-12, with the labels that each got.

#719 XEP-0001: add state transition Proposed -> Experimental
  xep-0001.xml
Labels: Needs Board

#724 MIX CORE (XEP-0369) update
  xep-0369.xml
Labels: Needs Author

#725 XEP-0363: added implementation note on CORS header
  xep-0363.xml
Labels: Ready To Merge

#726 MIX-PAM (XEP-0405) update
  xep-0405.xml
Labels: Ready To Merge

#728 XEP-0363: Added security consideration regarding proper isolation
  xep-0363.xml
Labels: Needs Author
