Repository xsf/xeps, pull requests merged in 2018-02, with the labels that each got.

#496 XEP-0300: Clarify textual content of the <hash/> element.
  xep-0300.xml
Labels: Ready To Merge

#587 XEP-0363: Http upload 0.5
  xep-0363.xml
Labels: Ready To Merge

#559 XEP-0045: Specify 333 status code
  xep-0045.xml
Labels: Needs Council

#588 XEP-0385: Fix HTTP-File-Upload typo
  xep-0385.xml
Labels: Editorial Change, Ready To Merge

#590 XEP-0385: Fix mismatched media-type start and end tags
  xep-0385.xml
Labels: Editorial Change, Ready To Merge
