Repository xsf/xeps, pull requests merged in 2018-03, with the labels that each got.

#585 XEP-0401: Use Data Form for IBR and fix error stanzas
  xep-0401.xml
Labels: Needs List Discussion, Needs Namespace Bump

#599 XEP-0379: minor editing
  xep-0379.xml
Labels: Needs Version Block, Ready To Merge

#597 XEP-0122: Do not put normative language into footnotes
  xep-0122.xml
Labels: Editorial Change, Ready To Merge

#593 XEP-0153: Clarify encoding of update hash
  xep-0153.xml
Labels: Ready To Merge

#600 XEP-0045: Implement stable IDs on Reflection
  xep-0045.xml
Labels: Ready To Merge

#603 Fix which witch is which
  xep-0045.xml
Labels: Editorial Change, Ready To Merge

#604 XEP-0163: Clarify how +notify works
  xep-0163.xml
Labels: Editorial Change, Needs Version Block, Ready To Merge

#605 XEP-0369: fix typo error
  xep-0369.xml
Labels: Editorial Change, Needs Version Block, Ready To Merge

#606 XEP-0107: Change the namespace of a private example
  xep-0107.xml
Labels: Editorial Change, Ready To Merge

#607 XEP-0369: Fix typos in channel control examples
  xep-0369.xml
Labels: Editorial Change, Needs Version Block, Ready To Merge

#609 XEP-0374: Add link to OMEMO XEP
  xep-0374.xml
Labels: Editorial Change, Ready To Merge

#610 Bookmark Harder
  inbox/bookmarks2.xml
Labels: ProtoXEP, Ready To Merge

#614 Add basic IM-NG spec
  inbox/im-ng.xml
Labels: ProtoXEP, Ready To Merge

#612 XEP-0122: Fix typo
  xep-0122.xml
Labels: Ready To Merge
