Repository xsf/xeps, pull requests merged in 2018-11, with the labels that each got.

#579 XEP-0198: Stream should be closed when 'h' value is to high.
  xep-0198.xml
Labels: Needs Council

#695 XEP-0060: Add an example on returning fewer items than requested
  xep-0060.xml
Labels: Needs Version Block, Ready To Merge

#714 XEP-0397: Bump "XEP-0397: Instant Stream Resumption" to 0.1.1
  xep-0397.xml
Labels: Editorial Change, Ready To Merge

#720 XEP-0205: Fix a namespace typo in an example
  xep-0205.xml
Labels: Editorial Change, Ready To Merge

#692 XEP-0060: correct "entity" to "<subscription/>"
  xep-0060.xml
Labels: Needs Council

#693 XEP-0060: Remove unused 'node' attribute on pubsub#event item
  xep-0060.xml
Labels: Needs Council
