Repository xsf/xeps, pull requests merged in 2018-09, with the labels that each got.

#699 XEP-0398: Fix usage of <strong/> vs. <cite/> and German vs. English double quotes
  xep-0398.xml
Labels: Editorial Change, Ready To Merge

#700 ProtoXEP: MUC Avatars
  inbox/muc-avatars.xml
Labels: ProtoXEP, Ready To Merge

#698 inbox/fsn: New revision; Add upload-finished state
  inbox/fsn.xml
Labels: Ready To Merge
