Repository xsf/xeps, pull requests merged in 2018-07, with the labels that each got.

#644 XEP-0373: Add pubsub example
  xep-0373.xml
Labels: Needs Version Block, Ready To Merge

#659 MIX-ADMIN - add mandatory nick option
  xep-0406.xml
Labels: Ready To Merge

#660 MIX-ANON Clarify use of PMs & Editorial
  xep-0404.xml
Labels: Needs Version Block, Ready To Merge

#661 MIX-CORE - default mandatry nicks and add nick to join
  xep-0369.xml
Labels: Ready To Merge

#662 MIX-PAM - Add blocking section
  xep-0405.xml
Labels: Ready To Merge

#663 MIX-PRESENCE - allow mapped resource; editorial
  xep-0403.xml
Labels: Ready To Merge

#665 Fix a typo in XEP-0384: replace "seperately" with "separately"
  xep-0384.xml
Labels: Editorial Change, Ready To Merge

#670 XEP-0373: Replace "ID" with "fingerprint"
  xep-0373.xml
Labels: Ready To Merge

#671 XEP-0198: Clarify the note about counters
  xep-0198.xml
Labels: Editorial Change, Ready To Merge

#674 XEP-0313 State explicitly that there shall be no 'to' attribute
  xep-0313.xml
Labels: Ready To Merge

#675 Tweak the 'complete' wording to reflect intent
  xep-0313.xml
Labels: Ready To Merge

#680 XEP-0402: Add missing dependency
  xep-0402.xml
Labels: Editorial Change, Ready To Merge

#669 XEP-0373: Fix node name of secret key node
  xep-0373.xml
Labels: Needs Version Block, Ready To Merge

#664 XEP-0045: Add implementation note about {jabber:x:conference}x payload
  xep-0045.xml
Labels: Needs Council, Needs Version Block

#685 XEP-0391: Fix typo: TI -> IV
  xep-0391.xml
Labels: Editorial Change, Ready To Merge
