Repository xsf/xeps, pull requests merged in 2019-01, with the labels that each got.

#729 Adopt deferred XEP-0394.
  xep-0394.xml
Labels: Ready To Merge

#730 XEP-0405: Fix style and XML-syntax issues
  xep-0405.xml
Labels: Editorial Change, Needs Version Block, Ready To Merge

#731 XEP-0369: Remove MIX xmlns from pubsub <item/>
  xep-0369.xml
Labels: Editorial Change, Ready To Merge

#734 XEP-0412: version 0.2.0
  xep-0412.xml
Labels: Ready To Merge

#735 ProtoXEP: Cryptographic Hash Function Recommendations for XMPP
  inbox/hash-recommendations.xml
Labels: ProtoXEP

#737 XEP-0412: update to version 0.4.0
  xep-0412.xml
Labels: Ready To Merge

#686 XEP-0384: Make examples use item id='current'
  xep-0384.xml
Labels: Ready To Merge
