Repository xsf/xeps, pull requests merged in 2019-07, with the labels that each got.

#798 s/to/two/
  xep-0368.xml
Labels: Editorial Change, Needs Version Block, Ready To Merge

#799 ProtoXEP: Anonymous unique occupant identifiers for MUCs
  inbox/occupant-id.xml
Labels: ProtoXEP, Ready To Merge

#800 ProtoXEP: Message Reactions
  inbox/reactions.xml
Labels: ProtoXEP, Ready To Merge

#690 XEP-0184: Make the schema require @id in <received/>
  xep-0184.xml
Labels: Ready To Merge

#789 XEP-0380: Add OMEMO encryption method
  xep-0380.xml
Labels: Ready To Merge

#794 xep-0371: fix gathering-complete text
  xep-0371.xml
Labels: Editorial Change, Needs Version Block, Ready To Merge

#795 MUC Self-Ping (XEP-0410): Clarify the feature string
  xep-0410.xml
Labels: Editorial Change, Needs Version Block, Ready To Merge

#797 XEP-0128: Remove 'unlikely' statement.
  xep-0128.xml
Labels: Needs Version Block, Ready To Merge
