Repository xsf/xeps, pull requests merged in 2019-02, with the labels that each got.

#749 Allow eliding of <unread> in XEP-0386
  xep-0386.xml
Labels: Ready To Merge

#739 XEP-0410: pre-LC and LC feedback
  xep-0410.xml
Labels: Needs Version Block, Ready To Merge

#743 XEP-0156: Add implementation notes suggesting CORS
  xep-0156.xml
Labels: Needs Version Block, Ready To Merge

#751 xep-0284: Fix xmlns in disco#info examples
  xep-0284.xml
Labels: Editorial Change, Needs Version Block, Ready To Merge

#753 Fix typos. "Chat Maker" should be "Chat Marker"
  xep-0333.xml
Labels: Editorial Change, Needs Version Block, Ready To Merge

#754 XEP-0410: added @by according to Council Feedback
  xep-0410.xml
Labels: Needs Version Block, Ready To Merge

#755 XEP-0261: Fixed sid in example 10.
  xep-0261.xml
Labels: Editorial Change, Needs Version Block, Ready To Merge

#756 XEP-0167: fixed wrong action in example 50
  xep-0167.xml
Labels: Editorial Change, Needs Version Block, Ready To Merge

#759 XEP-0260: mode attr must not be included
  xep-0260.xml
Labels: Editorial Change, Needs Version Block, Ready To Merge

#761 XEP-0313 (editorial): add bumped version into changelog
  xep-0313.xml
Labels: Editorial Change, Ready To Merge

#744 XEP-0001: Clarify proposing Deferred XEPs for advancement to Draft
  xep-0001.xml
Labels: Needs Board, Needs Council
