Repository xsf/xeps, pull requests merged in 2019-06, with the labels that each got.

#745 XEP-0234: Use <hash-used/> to signify the hash function being used, instead of an (invalid) empty <hash/>
  xep-0234.xml
Labels: Needs Version Block, Ready To Merge

#750 XEP-0300: remove content which has been moved to XEP-0414
  xep-0300.xml
Labels: Ready To Merge

#758 XEP-0060: Expose pubsub#access_model and pubsub#publish_model
  xep-0060.xml
Labels: Needs Version Block, Ready To Merge

#791 Add Stanza Content Encryption to the inbox
  inbox/xep-sce.xml
Labels: ProtoXEP, Ready To Merge

#792 Fix shortname of XEP-0315: Data Forms XML Element
  xep-0315.xml
Labels: Editorial Change, Needs Version Block, Ready To Merge
