Repository xsf/xeps, pull requests merged in 2019-12, with the labels that each got.

#861 Add ProtoXEP: Character counting in message bodies
  inbox/charcount.xml
Labels: Ready To Merge

#858 Preparation
  xep-0328.xml
Labels: Needs Version Block

#860 XEP-0422: s/reactions/message fastening
  xep-0422.xml
Labels: Needs Version Block

#857 XEP-0284: Fix examples
  xep-0284.xml
Labels: Ready To Merge

#859 fix missing "of" in xep 0280
  xep-0280.xml
Labels: Needs Version Block

#865 ProtoXEP: User-defined Data Transfer
  inbox/udt.xml
Labels: ProtoXEP

#864 ProtoXEP: MAM Fastening Collation
  inbox/mamfc.xml
Labels: ProtoXEP, Ready To Merge

#868 Update Fastening for list feedback
  xep-0422.xml
Labels: Ready To Merge

#869 Initial draft of SIG-E2EE
  inbox/sige2ee.xml
Labels: ProtoXEP, Ready To Merge
