Repository xsf/xeps, pull requests merged in 2019-05, with the labels that each got.

#779 XEP-0184: add a box about types and JIDs
  xep-0184.xml
Labels: Needs Version Block, Ready To Merge

#781 XEP-0308. Correct contents only
  xep-0308.xml
Labels: Needs Version Block, Ready To Merge

#784 XEP-0308: relax from-full-JID requirement
  xep-0308.xml
Labels: Needs Version Block, Ready To Merge

#785 XEP-0260: Replace broken link with archive.org
  xep-0260.xml
Labels: Editorial Change, Needs Version Block, Ready To Merge

#787 XEP-0045: kill GC1.0 with fire
  xep-0045.xml
Labels: Needs Version Block, Ready To Merge

#788 XEP-0414: remove reference to hashes namespace
  xep-0414.xml
Labels: Ready To Merge

#790 XEP-0405: Fix namespace typo in example
  xep-0405.xml
Labels: Editorial Change, Ready To Merge

#778 XEP-0280: Rewrite of the 'Messages Eligible for Carbons Delivery' section
  xep-0280.xml
Labels: Needs Council
