Repository xsf/xeps, pull requests merged in 2019-04, with the labels that each got.

#746 XEP-0060: Add missing @publisher in pubsub schema
  xep-0060.xml
Labels: Needs Council

#747 XEP-0084: Bump the maximum of @width and @height to 65535
  xep-0084.xml
Labels: Ready To Merge

#757 Update Justin K email
  xep.ent
Labels: Ready To Merge

#776 Fix missing attribute value apostrophe
  xep-0367.xml
Labels: Editorial Change, Ready To Merge

#777 xep-0280: Fix off-by-one in dependency
  xep-0280.xml
Labels: Editorial Change, Needs Version Block, Ready To Merge
