Repository xsf/xeps, pull requests merged in 2019-03, with the labels that each got.

#763 Automatic Trust Transfer
  inbox/automatic-trust-transfer.xml
Labels: ProtoXEP, Ready To Merge

#766 Update references to new XEPs and RFCs
  xep-0415.xml
  xep-0416.xml
  xep.ent
Labels: Editorial Change, Ready To Merge

#767 Mix CORE - XEP-0369
  xep-0369.xml
Labels: Ready To Merge

#768 Mix PAM - XEP-0405
  xep-0405.xml
Labels: Ready To Merge

#769 Fix typo in XEP-0199
  xep-0199.xml
Labels: Editorial Change, Needs Version Block, Ready To Merge

#770 XEP-0277: Fix typos/wording
  xep-0277.xml
Labels: Editorial Change, Needs Version Block, Ready To Merge

#772 XEP-0050: Fix variable name in example 14
  xep-0050.xml
Labels: Editorial Change, Needs Version Block, Ready To Merge

#773 XEP-0412: take over and push agenda
  xep-0412.xml
Labels: Ready To Merge
