Repository xsf/xeps, pull requests merged in 2019-08, with the labels that each got.

#796 XEP-0368: clarify what happens when a `.` target is published
  xep-0368.xml
Labels: Needs Version Block, Ready To Merge

#804 XEP-0413: Fix spelling mistakes and typos
  xep-0413.xml
Labels: Editorial Change, Needs Version Block, Ready To Merge

#806 XEP-0060: Add pubsub#public in Publish-Subscribe features
  xep-0060.xml
Labels: Needs Council, Needs Version Block

#811 XEP-0414: Drop dangling reference
  xep-0414.xml
Labels: Ready To Merge

#809 XEP-0364: Fix link to Daniels article
  xep-0364.xml
Labels: Editorial Change, Needs Version Block, Ready To Merge
