Repository xsf/xeps, pull requests merged in 2019-09, with the labels that each got.

#813 Forked XEP-0412 into Compliance Suite 2020
  inbox/cs-2020.xml
Labels: ProtoXEP, Ready To Merge

#816 ProtoXEP: Message fastening
  inbox/fasten.xml
Labels: ProtoXEP

#805 XEP-0060: Add a pubsub#rsm disco#info feature to clear confusion
  xep-0060.xml
Labels: Needs Council, Needs Version Block

#812 XEP-0084: Bump bytes datatype from unsignedShort to unsignedInteger
  xep-0084.xml
Labels: Needs Council

#822 XEP-0280: negative Carbons example
  xep-0280.xml
Labels: Needs Version Block, Ready To Merge

#833 New protoXEP: Message Moderation
  inbox/message-moderation.xml
Labels: ProtoXEP, Ready To Merge
