Repository xsf/xeps, pull requests merged in 2020-02, with the labels that each got.

#890 XEP-0430 Inbox Summit 24 Updates
  xep-0430.xml
Labels: Ready To Merge

#889 XEP-0357: Fix Enabling Notifications URL
  xep-0357.xml
Labels: Editorial Change, Needs Version Block, Ready To Merge

#893 ProtoXEP: Trust Messages
  inbox/trust-messages.xml
Labels: ProtoXEP, Ready To Merge

#892 XEP-0402 Last Call Comments
  xep-0402.xml
Labels: Ready To Merge

#891 ProtoXEP: Resubmit UDT as Simple JSON Messaging
  inbox/udt.xml
Labels: Ready To Merge

#895 ProtoXEP: Extended Channel Search
  inbox/extended-channel-search.xml
Labels: ProtoXEP
