Repository xsf/xeps, pull requests merged in 2020-05, with the labels that each got.

#940 caps: fix complex generation example by adding missing form field type
  xep-0115.xml
Labels: Editorial Change, Needs Version Block, Ready To Merge

#935 XEP-0004: clarify that the submitting entity may omit optional fields
  xep-0004.xml
Labels: Needs Council, Needs Version Block

#934 XEP-0167: add rtcp-mux element
  xep-0167.xml
  xep.ent
Labels: Needs Council, Needs Version Block

#918 XEP-0436: Updates based on list feedback
  xep-0436.xml
Labels: Ready To Merge

#953 XEP-0411: Fix (typo) XEP numbers
  xep-0411.xml
Labels: Editorial Change, Ready To Merge

#952 XEP-0402: Fix closing tags in examples
  xep-0402.xml
Labels: Editorial Change, Needs Version Block, Ready To Merge

#950 XEP-0414: Reverse SHOULD/MUST for Blake2b algorithms
  xep-0414.xml
Labels: Ready To Merge

#951 XEP-0402: Add schema
  xep-0402.xml
Labels: Editorial Change, Needs Version Block, Ready To Merge

#948 Add SASL Channel-Binding Capability ProtoXEP to inbox/
  inbox/xep-sasl-cb-types.xml
Labels: ProtoXEP, Ready To Merge

#947 XEP-0389 readability overhaul
  xep-0389.xml
Labels: Ready To Merge

#943 XEP-0068: Clarify FORM_TYPE field type on 'submit' type forms
  xep-0068.xml
Labels: Needs Council

#946 XEP-0393: editorial changes from LC feedback
  xep-0393.xml
Labels: Editorial Change, Ready To Merge
