Repository xsf/xeps, pull requests merged in 2020-01, with the labels that each got.

#871 charcount 0.2: Include feedback/clarifications from list
  xep-0426.xml
Labels: Ready To Merge

#870 XEP-0401: update pre-authenticated IBR
  xep-0401.xml
Labels: Needs Version Block, Ready To Merge

#877 Bump copyright year to 2020
  LICENSE.txt
  examples.xsl
  protopage.xsl
  ref.xsl
  xep-0001.xml
  xep-0292.xml
  xep.dtd
  xep.ent
  xep.xsd
Labels: Ready To Merge

#875 XEP-0379: Fix typos
  xep-0379.xml
Labels: Editorial Change, Needs Version Block, Ready To Merge

#872 XEP-0393: make span rules match examples
  xep-0393.xml
Labels: Ready To Merge

#884 ProtoXEP: Inbox
  inbox/inbox.xml
Labels: ProtoXEP, Ready To Merge

#883 ProtoXEP: Full Text Search in MAM
  inbox/fulltext.xml
Labels: ProtoXEP, Ready To Merge

#882 Update Dave Cridland email address
  xep.ent
Labels: Editorial Change, Ready To Merge

#880 XEP-0363: refined requirements and security considerations after LC
  xep-0363.xml
Labels: Ready To Merge
