Repository xsf/xeps, pull requests merged in 2020-09, with the labels that each got.

#977 XEP-0060: Fix minor typo in form example
  xep-0060.xml
Labels: Editorial Changes, Needs Version Block, Ready To Merge

#976 XEP-0060: Add missing querytype 'retrieve' action and 'item' key to registry submission
  xep-0060.xml
Labels: Needs Council

#985 XEP-0167: Add missing required attribute in schema for encryption element
  xep-0167.xml
Labels: Editorial Changes, Needs Version Block, Ready To Merge

#982 Fix reference to configuration in XEP-0313
  xep-0313.xml
  xep.ent
Labels: Editorial Changes, Needs Version Block, Ready To Merge

#978 XEP template: add a section with various XEP XML examples
  xep-template.xml
Labels: Editorial Changes, Ready To Merge

#980 Draft: Compliance Suite 2021: copied from XEP-423
  inbox/cs-2021.xml
Labels: ProtoXEP, Ready To Merge
