Repository xsf/xeps, pull requests merged in 2020-06, with the labels that each got.

#954 XEP-0402: schema: <extensions/> is optional
  xep-0402.xml
Labels: Editorial Changes, Needs Version Block, Ready To Merge

#958 XEP-0384: Incorporate feedback from Sofía Celi
  xep-0384.xml
Labels: Needs Version Block, Ready To Merge

#957 XEP-0393: remove disabling individual spans/blocks
  xep-0384.xml
Labels: Ready To Merge

#960 XEP-0329: Fix example 7, remove superfluous 'node' attribute
  xep-0329.xml
Labels: Editorial Changes, Needs Version Block, Ready To Merge

#959 XEP-0156: reorganize stating XRD/JRD requirements
  xep-0156.xml
Labels: Needs Council, Needs Version Block

#596 XEP-0390: Explain that ASCII Seperators are invalid only in XML *1.0*
  xep-0390.xml
Labels: Ready To Merge
