Repository xsf/xeps, pull requests merged in 2020-03, with the labels that each got.

#900 Don’t output invalid <di/> element in HTML
  xep.xsl
Labels: Editorial Change, Ready To Merge

#899 XEP-0369: Fix MIX typos, indentation, wording
  xep-0369.xml
Labels: Editorial Change, Needs Version Block, Ready To Merge

#897 XEP-0428: close <subject/>
  xep-0428.xml
Labels: Editorial Change, Needs Version Block, Ready To Merge

#903 XEP-0384: OMEMO version 0.4
  xep-0384.xml
Labels: Ready To Merge

#902 XEP-0343: fixed typo mlns->xmlns
  xep-0343.xml
Labels: Editorial Change, Needs Version Block, Ready To Merge

#901 Add support for section5 in stylesheet
  xep-0343.xml
Labels: Editorial Change, Ready To Merge

#906 Added rfc8445 entity as a dependency of PR 905
  xep.ent
Labels: Editorial Change, Ready To Merge

#910 XEP-0167: Add namespace to potentially misleading example
  xep-0167.xml
Labels: Editorial Change, Ready To Merge

#908 XEP-0384: OMEMO Encryption
  xep-0384.xml
Labels: Needs Author, Needs Version Block

#917 New ProtoXEP: MUC presence versioning
  inbox/muc-presence-versioning.xml
Labels: ProtoXEP

#914 XEP-0369: Add missing disco#info feature in examples, and fix xlns→xmlns typo
  xep-0369.xml
Labels: Editorial Change, Ready To Merge

#915 XEP-0332: Fix spelling of JavaScript
  xep-0332.xml
Labels: Editorial Change, Needs Version Block, Ready To Merge

#898 XEP-0060: Specify that empty <item/> are invalid on publish
  xep-0060.xml
Labels: Needs Council
