Repository xsf/xeps, pull requests merged in 2020-11, with the labels that each got.

#995 XEP-0359: Correct example caption
  xep-0359.xml
Labels: Editorial Changes, Needs Version Block, Ready To Merge

#996 MIX: Correct indentation, sentences and examples
  xep-0369.xml
  xep-0405.xml
  xep-0407.xml
Labels: Editorial Changes, Needs Version Block, Ready To Merge

#994 XEP-0420: Fix misspelling of 'whose'
  xep-0420.xml
Labels: Editorial Changes, Needs Version Block, Ready To Merge

#993 XEP-0438: update to match draft-ietf-kitten-password-storage-01
  xep-0438.xml
Labels: Ready To Merge

#1006 XEP-0389: error if client selects an invalid flow
  xep-0389.xml
Labels: Needs Version Block, Ready To Merge

#1005 Change title for ProtoXEPs
  docs/TRIAGING.md
Labels: Ready To Merge

#1002 Add XEP proposals for file sharing and stickers
  inbox/esfs.xml
  inbox/file-metadata.xml
  inbox/sfs.xml
  inbox/stickers.xml
  xep.ent
Labels: ProtoXEP, Ready To Merge
