Repository xsf/xeps, pull requests merged in 2020-08, with the labels that each got.

#974 XEP-0440: Version 0.2.0 of "XEP-0440: SASL Channel-Binding Type Capability"
  xep-0440.xml
Labels: Ready To Merge

#973 XEP-0313: Correct MAM UID "not-found" note
  xep-0313.xml
Labels: Needs Version Block, Ready To Merge

#969 XEP-0045 v1.33.0
  xep-0045.xml
Labels: Needs Council

#963 XEP-0178: Clarify SASL-EXTERNAL specification when s2s auth fails
  xep-0178.xml
Labels: Needs Council, Needs List Discussion, Needs Version Block
