Repository xsf/xeps, pull requests merged in 2020-10, with the labels that each got.

#987 XEP-0277: Add atom:generator element in examples to encourage its use
  xep-0277.xml
Labels: Editorial Changes, Needs Version Block, Ready To Merge

#932 XEP-0384: Version 0.7.0
  xep-0384.xml
Labels: Ready To Merge

#923 XEP-OMEMO (384): add hint to PubSub 'persistent-items' feature
  xep-0384.xml
Labels: Needs Version Block, Ready To Merge

#905 XEP-0371: migrate from RFC 5245 to 8445
  xep-0371.xml
Labels: Ready To Merge

#598 XEP-0050. Try to clarify usage of 'execute'
  xep-0050.xml
Labels: Ready To Merge

#990 XEP-0443: added section about a/v calls
  xep-0443.xml
Labels: Needs Version Block, Ready To Merge
