Repository xsf/xeps, pull requests merged in 2020-07, with the labels that each got.

#968 XEP-0420: Revision 0.3.0
  xep-0420.xml
Labels: Ready To Merge

#965 XEP-0162: Fix small typos
  xep-0162.xml
Labels: Editorial Changes, Ready To Merge

#967 XEP-0156: Mention Web Host Metadata Link format in abstract
  xep-0156.xml
Labels: Editorial Changes, Needs Version Block, Ready To Merge
