Repository xsf/xeps, pull requests merged in 2020-12, with the labels that each got.

#1003 XEP-0434: Release version 0.2.0
  xep-0434.xml
Labels: Ready To Merge

#1004 ProtoXEP: Automatic Trust Management (ATM)
  inbox/automatic-trust-management.xml
Labels: ProtoXEP, Ready To Merge

#1016 Fix mixed spaces/tabs in the template
  xep-template.xml
Labels: Ready To Merge

#1017 inbox: add new protoxep: Stanza Multiplexing
  inbox/mux.xml
Labels: ProtoXEP, Ready To Merge

#1018 XEP-0372: Determine substring indexing convention
  xep-0372.xml
Labels: Needs Version Block, Ready To Merge
