Repository xsf/xeps, pull requests merged in 2021-08, with the labels that each got.

#1092 Revert `pubsub#metadata` to `pubsub#meta-data`.
  xep-0060.xml
  xep-0214.xml
  xep-0248.xml
Labels: Needs Version Block, Ready To Merge

#1098 XEP-0429: Add discussion venues
  xep-0429.xml
Labels: Ready To Merge

#1099 XEP-0313: add implementation considerations
  xep-0313.xml
Labels: Ready To Merge

#1100 XEP-0001: change "Draft" to "Stable"
  xep-0001.xml
  xep.xsl
Labels: Ready To Merge

#1101 XEP-0082: Small orthographic corrections
  xep-0082.xml
Labels: Ready To Merge, Editorial Changes, Needs Version Block

#1103 XEP-0215: Fix wrong 'type' on response
  xep-0215.xml
Labels: Ready To Merge, Editorial Changes, Needs Version Block
