Repository xsf/xeps, pull requests merged in 2021-09, with the labels that each got.

#1096 XEP-0060: remove exception for last item when purging a node
  xep-0060.xml
Labels: Ready To Merge

#1064 XEP-0227: New revision 1.1
  xep-0227.xml
Labels: Needs Council

#1000 XEP-0384: Release version 0.8.0
  xep-0384.xml
Labels: Needs Author
