Repository xsf/xeps, pull requests merged in 2021-04, with the labels that each got.

#1049 XEP-0393: further changes for clarity when reading
  xep-0393.xml
Labels: Editorial Changes, Ready To Merge

#998 XEP-0420: Release version 0.4.0
  xep-0420.xml
Labels: Ready To Merge

#1052 xep.xsl: produce BibLaTeX entry
  xep.xsl
Labels: Editorial Changes, Needs Editor Action
