Repository xsf/xeps, pull requests merged in 2021-03, with the labels that each got.

#1038 XEP-0452: Fix reference to Stanza Forwarding
  xep-0313.xml
Labels: Editorial Changes, Ready To Merge

#1040 XEP-0313: remove "FIXME" comment
  xep-0313.xml
Labels: Editorial Changes, Needs Version Block, Ready To Merge

#1045 ProtoXEP: Content Rating Labels
  inbox/content-ratings.xml
Labels: ProtoXEP, Ready To Merge

#1046 XEP-0280: take over XEP maintenance
  xep-0280.xml
Labels: Needs Version Block, Ready To Merge

#1044 xep-0294: add mapping for a=extmap-allow-mixed
  xep-0294.xml
  xep.ent
Labels: Needs Version Block, Ready To Merge
