Repository xsf/xeps, pull requests merged in 2021-07, with the labels that each got.

#1086 XEP-0383: add listing of JIDs
  xep-0383.xml
  xep.ent
Labels: Ready To Merge

#1088 XEP-0369 fix date format
  xep-0369.xml
Labels: Editorial Changes, Ready To Merge

#1091 ProtoXEP: Pubsub Caching Hints
  inbox/pubsub-caching-hints.xml
Labels: ProtoXEP, Ready To Merge

#1094 XEP-0413: version 0.2
  xep-0413.xml
Labels: Ready To Merge

#1095 ProtoXEP: Disco Feature Attachment
  inbox/disco-feature-attachment.xml
Labels: ProtoXEP, Ready To Merge
