Repository xsf/xeps, pull requests merged in 2021-06, with the labels that each got.

#848 XEP-0292: Recommend using contact bare JIDs as item IDs
  xep-0292.xml
Labels: Needs Version Block, Ready To Merge

#1068 ProtoXEP: new protoXEP for pre-auth key generation
  inbox/preauth-ibr.xml
Labels: ProtoXEP, Ready To Merge

#1066 XEP-0124: Fix incorrect attribute name in text
  xep-0124.xml
Labels: Needs Version Block, Ready To Merge

#1071 ProtoXEP: Moved 2.0
  inbox/moved2.xml
Labels: ProtoXEP, Ready To Merge

#1074 XSLT: Use HTTPS for every common link
  xep.xsl
Labels: Ready To Merge

#1075 XSLT: Use lang='en' on the html root
  xep.xsl
Labels: Ready To Merge

#1072 XEP-0458 Code of Conduct comments
  xep-0458.xml
Labels: Needs Version Block, Ready To Merge
