Repository xsf/xeps, pull requests merged in 2021-01, with the labels that each got.

#1020 XEP-0372: Use codepoints for references
  xep-0372.xml
Labels: Ready To Merge

#1021 XEP-0177: Made type optional in the schema
  xep-0177.xml
Labels: Editorial Changes, Ready To Merge

#1022 Inbox: add new protoXEP: MUC Mention Notifications
  inbox/muc-mention-notifications.xml
Labels: ProtoXEP, Ready To Merge

#1008 XEP-0047: fix incorrect max sequence number
  xep-0047.xml
Labels: Needs Version Block, Ready To Merge

#1014 XEP-0176: Improve compatibility with WebRTC clients
  xep-0176.xml
Labels: Ready To Merge

#1024 XEP-0104: Fix examples by adding missing 'http:' prefix to child elements
  xep-0104.xml
Labels: Editorial Changes, Needs Version Block, Ready To Merge

#1025 XEP-0447: Fix typo in example
  xep-0447.xml
Labels: Editorial Changes, Ready To Merge

#1026 Resubmit OMEMO Media Sharing on Historical track
  inbox/omemo-media-sharing.xml
Labels: ProtoXEP, Ready To Merge

#1027 ProtoXEP: DOAP usage in XMPP
  inbox/doap-usage-in-xmpp.xml
Labels: ProtoXEP, Ready To Merge

#1001 XEP-0393: clarify rules for span directives
  xep-0393.xml
Labels: Needs Council, Needs Version Block

#1023 XEP-0434: Release version 0.3.0
  xep-0434.xml
Labels: Ready To Merge

#1028 ProtoXEP: "Service Outage Status"
  inbox/service-outage-status.xml
Labels: ProtoXEP, Ready To Merge

#1029 prettify: add link to source and license information
  inbox/service-outage-status.xml
Labels: Ready To Merge
