Repository xsf/xeps, pull requests merged in 2024-09, with the labels that each got.

#1390 XEP-0474: Fix typos and adapt attack-model section to new simplified protocol
  xep-0474.xml
Labels: Needs Author

#1379 XEP-0114: Add missing 'approver' element.
  xep-0114.xml
Labels: Needs Council, Needs Version Block

#1380 XEP-0126: Add missing 'approver' element.
  xep-0126.xml
Labels: Needs Council, Needs Version Block

#1382 XEP-0188: Add missing 'approver' element.
  xep-0188.xml
Labels: Needs Editor Action

#1383 XEP-0190: Add missing 'approver' element.
  xep-0190.xml
Labels: Needs Council, Needs Version Block

#1384 XEP-0205: Add missing 'approver' element.
  xep-0205.xml
Labels: Needs Council, Needs Version Block

#1370 XEP-0045: Add explicit error definition when non-owners attempt to use owner-specific functionality
  xep-0045.xml
Labels: Needs Council

#1139 XEP-0272: Update to adjust for current XMPP protocols
  xep-0272.xml
Labels: Needs Author

#1387 XEP-0004: Empty and absent values
  xep-0004.xml
Labels: Needs Council

#1366 XEP-0264: Restrict 'width' and 'height' to the 0..65535 range
  xep-0264.xml
Labels: Needs Editor Action
