Repository xsf/xeps, pull requests merged in 2024-03, with the labels that each got.

#1328 XEP-0333: Display Markers. Remove received and ack
  xep-0333.xml
Labels: Needs Editor Action

#1293 XEP-0060: Release version 1.26.0
  xep-0060.xml
Labels: Needs Changes

#780 XEP-0001: Make only editorial changes affect Deferred state
  xep-0001.xml
Labels: Needs Council, Needs Board

#1324 XEP-0313: Add XEP-0136 to superseded specifications
  xep-0313.xml
Labels: Needs Council, Needs Version Block

#1336 XEP-0334: rev 0.3.1: incorporate Last Call feedback
  xep-0334.xml
Labels: Needs Editor Action

#1333 XEP-0388: add missing elements to XML Schema
  xep-0388.xml
Labels: Needs Author

#1326 Small fixes for 0424
  xep-0424.xml
Labels: Needs Author
