Repository xsf/xeps, pull requests merged in 2025-04, with the labels that each got.

#706 Update BCP 14 language to comply with RFC 8174
  xep.xsl
Labels: Needs Version Block

#1431 XEP-0313: Fix typo ('staza'->'stanza')
  xep-0313.xml
Labels: Needs Council, Needs Version Block

#1433 XEP-0455: only keep a minimal core
  xep-0455.xml
Labels: Needs Author
