Repository xsf/xeps, pull requests merged in 2025-01, with the labels that each got.

#1413 XEP-0421 v0.3.0
  xep-0421.xml
Labels: Needs Council

#1420 XEP-0453: Replace my author block with the entity
  xep-0453.xml
Labels: Needs Author, Needs Version Block

#1422 XEP-0474: Use better value delimiter
  xep-0474.xml
Labels: Needs Author

#1421 XEP-0480: Fix SCRAM upgrade description and XML schema
  xep-0474.xml
Labels: Needs Author

#1419 XEP-0424: Modifications in response to Last-Call feedback.
  xep-0424.xml
Labels: Needs Author
